{{- if .Values.uiIngress.enabled -}}
{{- $fullName := include "mpd.fullname" . -}}
{{- $servicePort := .Values.ports.ympd -}}
{{- $ingressPath := .Values.uiIngress.path -}}
apiVersion: {{ template "mpd.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ui
  labels:
    app: {{ template "mpd.name" . }}
    chart: {{ template "mpd.chart" . }}
    release: {{ .Release.Name }}
{{- with .Values.uiIngress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}

{{- with .Values.uiIngress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.uiIngress.ingressClassName }}
  ingressClassName: {{ .Values.uiIngress.ingressClassName }}
{{- end }}
{{- if .Values.uiIngress.tls }}
  tls:
  {{- range .Values.uiIngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.uiIngress.hosts }}
    - http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-ui
                port:
                  number: {{ $servicePort }}
      {{- if . }}
      host: {{ . | quote }}
      {{- end }}
  {{- end }}
{{- end }}