syncthingConfig: ""

peers:
# - podName: "matchbox-0"
#   syncthingCert:
#   syncthingKey:

matchboxSecret:
  # ca: "ca"
  # cert: "cert"
  # key: "key"

syncthingHomePath: "/var/lib/syncthing"
sharedDataPath: "/var/tmp/matchbox"

StatefulSet:
  replicaCount: 2
  updateStrategy: "RollingUpdate"
  minReadySeconds: 20

images:
  matchbox: "quay.io/poseidon/matchbox:latest"
  syncthing: "docker.io/syncthing/syncthing:latest"

ports:
  syncthingPeer: 22000
  matchbox: 8080
  matchboxAPI: 8081

affinity: {}
tolerations: {}

hostNetwork:
  enabled: false

syncService:
  port: 22000

service:
  type: NodePort
  clusterIP: ~
  port: 8080
  nodePort: 30010

apiService:
  type: NodePort
  clusterIP: ~
  port: 8081
  nodePort: 30011

tftpdService:
  type: NodePort
  clusterIP: ~
  port: 69
  nodePort: 69