peers:
# - serviceIP: 10.96.0.20
#   podName:
#   dhcp4Config: 
#   ctrlAgentConfig:

sharedDataPath: "/var/lib/kea"

StatefulSet:
  replicaCount: 2
  updateStrategy: "RollingUpdate"
  minReadySeconds: 20

images:
  kea: "ghcr.io/randomcoww/kea:2.0.2"
  tftpd: "ghcr.io/randomcoww/tftpd-ipxe:20220804"

ports:
  keaPeer: 22000
  tftpd: 69

affinity: {}
tolerations: {}