kind: Service
apiVersion: v1
metadata:
  name: {{ template "external-dns.fullname" . }}
  labels:
    app: {{ template "external-dns.name" . }}
    chart: {{ template "external-dns.chart" . }}
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{end}}
  ports:
{{ include "coredns.servicePorts" . | indent 2 -}}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{- range $i , $ip := .Values.service.externalIPs }}
  - {{ $ip }}
{{- end }}
{{- end }}
  selector:
    app: {{ template "external-dns.name" . }}
    release: {{ .Release.Name }}