config:
  # filesystem_charset: UTF-8
audioOutputs:
# - name: flac-3
#   port: 8082
#   config:
#     tags: "yes"
#     format: "48000:24:2"
#     always_on: "yes"
#     encoder: flac
#     compression: 3
#     max_clients: 0
# - name: lame-9
#   port: 8083
#   config:
#     tags: "yes"
#     format: "48000:24:2"
#     always_on: "yes"
#     encoder: lame
#     quality: 9
#     max_clients: 0

tls:
  enabled: true

minioEndPoint: http://minio.default.svc:9000
minioBucket: music

# Needs common local database - only works with 1 PV
persistence:
  accessMode: ReadWriteOnce
  size: 100M
  storageClass: local-path

images:
  mpd: ghcr.io/randomcoww/mpd:0.23.8
  mympd: ghcr.io/randomcoww/mympd:latest
  rclone: docker.io/rclone/rclone:latest

ports:
  mympd: 8080
  rclone: 8081

mpdCachePath: /mpd/cache

affinity: {}
tolerations: {}

service:
  type: ClusterIP

uiService:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    # "cert-manager.io/cluster-issuer":                    "letsencrypt"
    # "nginx.ingress.kubernetes.io/auth-response-headers": "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
    # "nginx.ingress.kubernetes.io/auth-signin":           "https://auth.local"
    # "nginx.ingress.kubernetes.io/auth-snippet": |
    #   proxy_set_header X-Forwarded-Method $request_method;
    # "nginx.ingress.kubernetes.io/auth-url":              "http://ath.default.svc/api/verify"
  ingressClassName: nginx
  tls:
  # - secretName: chart-example-tls
  #   hosts:
  #     - chart-example.local
  hosts:
  # - chart-example.local

uiIngress:
  enabled: true
  annotations:
    # "cert-manager.io/cluster-issuer":                    "letsencrypt"
    # "nginx.ingress.kubernetes.io/auth-response-headers": "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
    # "nginx.ingress.kubernetes.io/auth-signin":           "https://auth.local"
    # "nginx.ingress.kubernetes.io/auth-snippet": |
    #   proxy_set_header X-Forwarded-Method $request_method;
    # "nginx.ingress.kubernetes.io/auth-url":              "http://ath.default.svc/api/verify"
  path: /
  ingressClassName: nginx
  tls:
  # - secretName: chart-example-tls
  #   hosts:
  #     - chart-example.local
  hosts:
  # - chart-example.local