name: Renovate bot
on:
  workflow_dispatch:
  schedule:
  - cron: "0 16 * * *"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: renovate-${{ github.event.repository.name }}
    container:
      image: reg.cluster.internal/randomcoww/renovate:latest@sha256:85661849495e137db7805e35fb79290a33f4ae52c589fa8a395a7d2c5d60e768
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - name: Check for updates
      env:
        RENOVATE_PLATFORM: github
        RENOVATE_AUTODISCOVER: false
        # RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }} # pass RENOVATE_TOKEN from runner
        RENOVATE_CONFIG_FILE: /tmp/renovate.json
      run: |
        cat > $RENOVATE_CONFIG_FILE <<EOF
        {
          "repositories": [
            "${{ github.repository }}"
          ]
        }
        EOF

        exec renovate-entrypoint.sh renovate